apiVersion: v1
kind: Service
metadata:
  name: charity-platform-charity-service
spec:
  selector:
    app: charity-platform-charity-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
