apiVersion: v1
kind: Service
metadata:
  name: charity-platform-discovery-service
spec:
  selector:
    app: charity-platform-discovery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8761
  type: ClusterIP
