CREATE SCHEMA IF NOT EXISTS public;
CREATE TABLE charity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    fundraising_goal DOUBLE PRECISION NOT NULL,
    creator_id BIGINT NOT NULL,
    paypal_email VARCHAR(255) NOT NULL,
    creation_date DATE NOT NULL,
    category VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);
