export const SET_DONATION_DRAFT = "SET_DONATION_DRAFT";
export const CLEAR_DONATION_DRAFT = "CLEAR_DONATION_DRAFT";
export const CREATE_AUTH_SUCCESS = "CREATE_AUTH_SUCCESS";
export const LOGOUT = "LOGOUT";
