apiVersion: apps/v1
kind: Deployment
metadata:
  name: charity-platform-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: charity-platform-api-gateway
  template:
    metadata:
      labels:
        app: charity-platform-api-gateway
    spec:
      containers:
        - name: charity-platform-api-gateway
          image: charityplatformacr.azurecr.io/charity-platform-api-gateway:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: azure
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 400m
