apiVersion: v1
kind: Service
metadata:
  name: charity-platform-api-gateway
spec:
  selector:
    app: charity-platform-api-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
